[package]
name = "basket"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
colored = "3.0.0"
envvars = "0.1.10"
rusqlite = { version = "0.37.0", features = ["bundled"] }
terminal-emoji = "0.4.1"
[dependencies.uuid]
version = "1.18.1"
# Lets you generate random UUIDs
features = [
    "v4",
]
